version: '2'

services:

  resume-make:
    build:
      context: .
      dockerfile: ./.docker/resume.dockerfile
    command: make
    container_name: resume-make
    image: resume-make
    volumes:
      - "C:/Users/duann/Documents/GitHub/pandoc_resume/resume_output"
